### ISSUE TITLE
Can't remove or rotate stickerView under other stickerView

### ISSUE THREAD

**Issue by Darktt** [chiahsien/CHTStickerView#1]
As your demo code, if **stickerViewA** _(content with UIImageView)_ the corner _(remove or rotate side)_ under and not full cover via **stickerViewB** _(content with UILabel)_, 
than I can't  remove or rotate **stickerViewA**.

I suggest you can select **stickerViewA** and bring it to front temporary,
and select other sticker or unselect **stickerViewA** push to really layer.

**Comment by chiahsien** [comment]
OK, thanks!
