### ISSUE TITLE
Resize without rotation

### ISSUE THREAD

**Issue by vadymus** [chiahsien/CHTStickerView#3]
This functionality would be fully complete if user can resize the view in different directions without it being rotated. I have seen this as a trend in many apps: one corner does a resize-rotate (done) and another corner does rotate only (can be easily done by adjusting your code). But how to resize the third corner without rotation so bounds can be easily adjusted to the touch location. This means resizing occurs unproportionally while the opposite corner is locked in its position? I tried this code but it does not perfectly work.
- (void)handleResizeGesture:(UIPanGestureRecognizer *)recognizer {
  CGPoint touchLocation = [recognizer locationInView:self.superview];
  CGPoint center = self.center;  
  switch (recognizer.state) {
  case UIGestureRecognizerStateBegan: {
      initialBounds = self.bounds;
      initialLocation = touchLocation;
      [self.delegate stickerViewDidBeginRotating:self];
      break;
  }  
  case UIGestureRecognizerStateChanged: {  
      CGRect resizedBounds = CGRectMake(0, 0,
                              initialBounds.size.width + touchLocation.x - initialLocation.x,
                              initialBounds.size.height + touchLocation.y - initialLocation.y);
      self.bounds = resizedBounds;  
      [self setNeedsDisplay];  
      [self.delegate stickerViewDidChangeRotating:self];
      break;
  }  
  case UIGestureRecognizerStateEnded:
      [self.delegate stickerViewDidEndRotating:self];
      break;
  default: break;
  }
  }

**Comment by chiahsien** [comment]
There are two reasons:

##### 1.

> Changing the bounds size grows or shrinks the view relative to its **center point**.

So, when you change the `bounds`, its `center` remains unchanged.

##### 2.

The formula you use:

``` objc
CGRect resizedBounds = CGRectMake(0, 0,
                                  initialBounds.size.width + touchLocation.x - initialLocation.x,
                                  initialBounds.size.height + touchLocation.y - initialLocation.y);
```

which assumes that the handler is at the **bottom-right** corner - which may not be the case you're using.

I believe that's why you can't get the codes work properly.

---

By the way, it always is a good practice to check if the `delegete` responds to a certain optional method before calling it.

``` objc
if ([self.delegate respondsToSelector:@selector(stickerViewDidBeginRotating:)]) {
  [self.delegate stickerViewDidBeginRotating:self];
}
```

Good luck!

**Comment by chiahsien** [comment]
Is everything OK?

**Comment by vadymus** [comment]
Yes, I understand your comment. Thank you (and sorry for delayed response). I do need however to find a solution to accomplish resizing freely in any direction while keeping the opposite corner unchanged. If you have an advice please let me know. If you can add this to your library as an improvement that would be even better.
Thank you in advance.
