### ISSUE TITLE
handleCloseGesture problem

### ISSUE THREAD

**Issue by glancashire** [chiahsien/CHTStickerView#4]
First: Thanks for the nice control!

There is a small problem in the handleCloseGesture routine: if you removeFromSuperview first, then the respondsToSelector returns false.

You should first call the delegate and then removeFromSuperview:
- (void)handleCloseGesture:(UITapGestureRecognizer *)recognizer {
  if ([self.delegate respondsToSelector:@selector(stickerViewDidClose:)]) {
      [self.delegate stickerViewDidClose:self];
  }
  [self removeFromSuperview];
  }

Kind Regards
Graham

**Comment by chiahsien** [comment]
Fixed, thanks!
